car_inventory/authentication/routes.py
from flask import Blueprint, render_template, request, redirect, url_for, flash
from car_inventory.forms import UserSignUpForm, UserSignInForm
from car_inventory.models import User, db
from werkzeug.security import check_password_hash
from flask_login import login_user, logout_user, login_required

auth = Blueprint('auth', __name__, template_folder="auth_templates")

@auth.route('/signup', methods = ['GET', 'POST'])
def signup():
    signupform = UserSignUpForm()
    try:
        if request.method == "POST" and signupform.validate_on_submit():
            email = signupform.email.data
            first_name = signupform.first_name.data
            last_name = signupform.last_name.data
            password = signupform.password.data

            user = User(email, first_name, last_name, password=password)
            db.session.add(user)
            db.session.commit()

            flash(f"You have successfully created a user account: {email}", "user-created")
            return redirect(url_for('auth.signin'))
    except:
        raise Exception("Invalid form data. Please check your form.")
    return render_template("signup.html", signupform=signupform)

@auth.route('/signin', methods = ['GET', 'POST'])
def signin():
    signinform = UserSignInForm()
    try:
        if request.method == "POST" and signinform.validate_on_submit():
            email = signinform.email.data
            password = signinform.password.data

            logged_user = User.query.filter(User.email == email).first()
            if logged_user and check_password_hash(logged_user.password, password):
                login_user(logged_user)
            
                flash(f"You have successfully logged in.", 'auth-success')
                return redirect(url_for('site.profile'))
            
            else:
                flash("Your email or password was entered incorrectly. Please try again.", "auth-failed")
                return redirect(url_for('auth.signin'))
    except:
        raise Exception("Invalid form data. Please try again.")

    return render_template("signin.html", signinform=signinform)

@auth.route('/logout')
@login_required
def logout():
    logout_user()
    return redirect(url_for('site.home'))

car_inventory/site/routes.py
from flask import Blueprint, render_template
from flask_login import login_required

site = Blueprint('site', __name__, template_folder='site_templates')

@site.route('/')
def home():
    return render_template('index.html')

@site.route('/profile')
@login_required
def profile():
    return render_template("profile.html")

car_inventory/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="UTF-8">
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<meta http-equiv="X-UA-Compatible" content="ie=edge">
<meta name="Description" content="Enter your description here"/>
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/5.1.0/css/bootstrap.min.css">
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.4/css/all.min.css">
<link rel="stylesheet" href="../static/css/main.css">
<title>Dog Inventory</title>
</head>
<body>
    <nav class="ct-nav">
        <div>
            <img src="../static/images/undraw_Dog_re_7980.png" alt="Dog Logo">
        </div>

        <div>
            <ul id="nav-list">
                <a href="{{ url_for('site.home') }}">
                    <li>Home</li>
                </a>
                {% if current_user.is_authenticated %}
                <a href="{{ url_for('site.profile') }}">
                    <li>Profile</li>
                </a>
                <a href="{{ url_for('auth.logout') }}">
                    <li>Logout</li>
                </a>
                {% else %}
                <a href="{{ url_for('auth.signin') }}">
                    <li>Sign In</li>
                </a>
                <a href="{{ url_for('auth.signup') }}">
                    <li>Sign Up</li>
                </a>
                {% endif %}
            </ul>
        </div>
    </nav>

    {% block content %}

    {% endblock content %}
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/2.9.2/umd/popper.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/5.1.0/js/bootstrap.min.js"></script>
</body>
</html>

car_inventory/templates/signinform.html
<form method="POST">
    {{ signinform.hidden_tag() }}
    <div class="form-group">
        <fieldset id="email-field">
            {{ signinform.email.label }}
            {{ signinform.email(class="form-control", placeholder="Enter Email")}}
        </fieldset>

        <fieldset id="pass-field">
            {{ signinform.password.label }}
            {{ signinform.password(class="form-control", placeholder="Enter Password")}}
        </fieldset>

        {{ signinform.submit_button(class="btn btn-secondary btn-block") }}
    </div>
</form>

car_inventory/templates/signupform.html
<form method="POST">
    {{ signupform.hidden_tag() }}
    <div class="form-group">
        <fieldset id="email-field">
            {{ signupform.email.label }}
            {{ signupform.email(class="form-control", placeholder="Enter Email")}}
        </fieldset>

        <fieldset id="first-field">
            {{ signupform.first_name.label }}
            {{ signupform.first_name(class="form-control", placeholder="Enter First Name")}}
        </fieldset>

        <fieldset id="last_field">
            {{ signupform.last_name.label }}
            {{ signupform.last_name(class="form-control", placeholder="Enter Last Name")}}
        </fieldset>

        <fieldset id="pass-field">
            {{ signupform.password.label }}
            {{ signupform.password(class="form-control", placeholder="Enter Password")}}
        </fieldset>

        {{ signupform.submit_button(class="btn btn-secondary btn-block") }}
    </div>
</form>